create extension if not exists pgcrypto;
create sequence if not exists gamezone_invoice_seq;
create table if not exists products(id text primary key,name text not null,category text not null,jod numeric(12,2) not null,usd numeric(12,2) not null,sar numeric(12,2) not null,active boolean not null default true);
insert into products(id,name,category,jod,usd,sar) values
('fortnite-vbucks-800','800 V-Bucks','Fortnite',4.5,6.5,24),('fortnite-vbucks-2400','2,400 V-Bucks','Fortnite',11,15.5,59),('fortnite-vbucks-4500','4,500 V-Bucks','Fortnite',16,23,80),('fortnite-vbucks-12500','12,500 V-Bucks','Fortnite',40,56.5,212),
('minecraft-2400','2,400 Minecoins','Minecraft',3,4.5,16),('minecraft-5270','5,270 Minecoins','Minecraft',5.5,8,30),('minecraft-8000','8,000 Minecoins','Minecraft',7.5,11,40),('minecraft-10850','10,850 Minecoins','Minecraft',8.5,12,45),
('rocket-500-credits','500 Credits','Rocket League',3.5,5,19),('rocket-1100-credits','1,100 Credits','Rocket League',6,8.5,32),('rocket-3100-credits','3,100 Credits','Rocket League',13,18.5,69),('rocket-6500-credits','6,500 Credits','Rocket League',25,35.5,133),
('fortnite-crew-monthly','Fortnite Crew — Monthly','Fortnite',3.5,5,19)
on conflict(id) do update set name=excluded.name,category=excluded.category,jod=excluded.jod,usd=excluded.usd,sar=excluded.sar,active=true;
create table if not exists orders(id uuid primary key default gen_random_uuid(),invoice_id text unique not null,currency text not null check(currency in ('JOD','USD','SAR')),total numeric(12,2) not null,status text not null default 'Pending' check(status in ('Pending','Processing','Completed','Cancelled')),discord_username text,note text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists order_items(id bigint generated by default as identity primary key,order_id uuid not null references orders(id) on delete cascade,product_id text not null references products(id),name text not null,quantity integer not null check(quantity between 1 and 50),unit_price numeric(12,2) not null,line_total numeric(12,2) not null);
alter table products enable row level security; alter table orders enable row level security; alter table order_items enable row level security;
create or replace function create_gamezone_order(p_currency text,p_items jsonb,p_discord_username text default '',p_note text default '') returns table(invoice_id text,total numeric,currency text,items jsonb,discord_username text,note text,created_at timestamptz) language plpgsql security definer set search_path=public as $$
declare v_order_id uuid; v_invoice text; v_total numeric:=0; x jsonb; p products%rowtype; v_qty int; v_price numeric; v_items jsonb:='[]'::jsonb;
begin
  if p_currency not in ('JOD','USD','SAR') then raise exception 'Invalid currency'; end if;
  if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 or jsonb_array_length(p_items)>30 then raise exception 'Invalid items'; end if;
  for x in select * from jsonb_array_elements(p_items) loop
    if not (x ? 'product_id') or not (x ? 'quantity') then raise exception 'Invalid item'; end if;
    v_qty:=(x->>'quantity')::int;
    if v_qty<1 or v_qty>50 then raise exception 'Invalid quantity'; end if;
    select * into p from products where id=x->>'product_id' and active=true;
    if not found then raise exception 'Invalid product'; end if;
    v_price:=case p_currency when 'JOD' then p.jod when 'USD' then p.usd else p.sar end;
    v_total:=v_total+v_price*v_qty;
    v_items:=v_items||jsonb_build_object('product_id',p.id,'name',p.name,'quantity',v_qty,'unit_price',v_price,'line_total',v_price*v_qty);
  end loop;
  v_invoice:='GZ-'||to_char(current_date,'YYYY')||'-'||lpad(nextval('gamezone_invoice_seq')::text,6,'0');
  insert into orders(invoice_id,currency,total,discord_username,note) values(v_invoice,p_currency,v_total,left(coalesce(p_discord_username,''),80),left(coalesce(p_note,''),500)) returning id,orders.created_at into v_order_id,created_at;
  for x in select * from jsonb_array_elements(v_items) loop
    insert into order_items(order_id,product_id,name,quantity,unit_price,line_total) values(v_order_id,x->>'product_id',x->>'name',(x->>'quantity')::int,(x->>'unit_price')::numeric,(x->>'line_total')::numeric);
  end loop;
  return query select v_invoice,v_total,p_currency,v_items,left(coalesce(p_discord_username,''),80),left(coalesce(p_note,''),500),created_at;
end; $$;
revoke all on function create_gamezone_order(text,jsonb,text,text) from public;
grant execute on function create_gamezone_order(text,jsonb,text,text) to anon,authenticated;
